# -*- coding: utf-8 -*-
"""EBAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSSntP0YD6A7bn5ODu-ejvBJOEuSYnLf
"""

primeiro_numero = input("primeiro numero:")
segundo_numero = input("segundo numero:")

primeiro_numero = int(primeiro_numero);
segundo_numero = int(segundo_numero);

soma = primeiro_numero + segundo_numero
print("A soma é:", soma)

subtração = primeiro_numero - segundo_numero
print("A subtração é:", subtração)

divisao = primeiro_numero / segundo_numero
print("A divisão é:", divisao)

multiplicação = primeiro_numero * segundo_numero
print("A multiplicação é:", multiplicação)

input("coloque o numero")
for numero in range(10):
    print(numero)
    if numero == 1:

        pass